### ISSUE TITLE
[Suggestion]: Show the mob's attributes (whether they are classified as undead, or arthopods)

### ISSUE THREAD

**Issue by TechPro424** [Fuzss/mobplaques#1]
### Suggestion (Required)

Show the mob's attributes (whether they are classified as undead, or arthopods)
This would be useful for the Smite and Bane Of Arthopods enchantments

**Comment by Fuzss** [comment]
Thanks for the suggestion, I don't think this is necessary. If you really need that information check out other mods such as Neat by Vazkii.
