### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Psychodeus** [Fuzss/mobplaques#11]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.0

### Mod Version (Required)

7.0.0

### Notes (Required)

![image](https://github.com/Fuzss/mobplaques/assets/93028949/51da1be8-e552-4597-9ddb-59ee696d1890)
![image](https://github.com/Fuzss/mobplaques/assets/93028949/26c18abe-f568-4169-a114-15ae6092c22b)

It's not working to configure the mod, instead it create this .bak file and when I'm in game the mod just not work as I edit. For example I edit to prefer to only show hp when I point cursor, not works.

**Comment by Fuzss** [comment]
Please edit the config in-game by installing the Forge Config Screens mod. The .bak files are usually created when there is a syntax error from manual editing.

**Comment by Psychodeus** [comment]
It's working now, but! When I select only show hp when I point cursor, I thought it follows the same max render distance for always show hp bar option. It was not, it renders only at hands reach.

![2023-08-28_23 04 03](https://github.com/Fuzss/mobplaques/assets/93028949/80e5bb28-86e6-42f3-9844-d43c5d72ef33)

**Comment by Fuzss** [comment]
Make sure `picked_entity` is set to `false`.

**Comment by Psychodeus** [comment]
I know, what I'm trying to say is, perhaps add option to show hp on max render distance with picked entity. Thanks.
