### ISSUE TITLE
[1.19.2 Fabric Bug] Errors in Log

### ISSUE THREAD

**Issue by itsdinkd** [Fuzss/mobplaques#2]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

the only one you have for fabric

### Notes (Required)

Starting world and there are some errors spammed in console. 

### latest.log (Optional)

https://gist.github.com/itsdinkd/0fbfdf53d034d8da8238ebf507de6694

**Comment by Fuzss** [comment]
Thanks for reporting!

Should be fixed in v4.0.1. Please reopen if it's not.
