### ISSUE TITLE
[Bug]: config continues to reset itself

### ISSUE THREAD

**Issue by itsdinkd** [Fuzss/mobplaques#3]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19

### Mod Version (Required)

fabric

### Notes (Required)

I'll edit the config, even with game off, and it creates a backup when it turns on and resets config. 

![image](https://user-images.githubusercontent.com/35115304/212737816-b2690b41-c4ae-47dc-8e38-f3381aec510b.png)

![image](https://user-images.githubusercontent.com/35115304/212737833-31d27c98-df7c-43f8-b117-8c35ddd992c3.png)

**Comment by Fuzss** [comment]
This issue seems to be related to Forge's config system (which I'm also using on Fabric). There is nothing I can do about it.

I can only recommend setting up a default config, so that when the config fails to load your desired values will be restored instead of the built-in defaults.

**Comment by Psychodeus** [comment]
I got this too.
