### ISSUE TITLE
[Suggestion]: Hide ARMOR & Toughness When HP Full config option

### ISSUE THREAD

**Issue by itsdinkd** [Fuzss/mobplaques#6]
### Suggestion (Required)

If you enable hide_when_full (Which normally would be enabled so you do not see a bunch of floating hearts by default) it renders this useless if the armor shows regardless.

- add a option to hide armor if hp is full
- add a option to hide troughness if hp is full

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/222928804-2dc4a8f0-3407-4877-bb32-d9d5d82354d2.png)

**Comment by Fuzss** [comment]
Added in v5.0.0 for 1.19.3.
