### ISSUE TITLE
[Bug]:  No config file located in the world instance config file folder for server

### ISSUE THREAD

**Issue by YngFox** [Fuzss/mobplaques#8]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.1

### Notes (Required)

Read your description on editing mod for server but there was no config file located anywhere in the server files. Any input on this would be greatly appreciated.

Thank you,

Ethan McCloud

**Comment by Fuzss** [comment]
there is no server config, only a client config for this one. that part of the description is from my template used for all mods
